### Teach Myself Array

#### Learn basic array fundamentals used for Data Science

In [1]:
import numpy as np

#### create 1 D array

In [2]:
my_mat = [1,2,3]

In [3]:
np.array(my_mat)

array([1, 2, 3])

#### create 3d array from list

In [4]:
my_2dmat = ([1,2,3],[4,5,6],[7,8,9])

In [5]:
np.array(my_2dmat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### create empty array in range

In [6]:
np.arange(1,5)

array([1, 2, 3, 4])

In [12]:
np.zeros((100,100))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

#### linspace = create array with range between number, and range. retstep to view step been done.

In [13]:
np.linspace(0,100,2)

array([  0., 100.])

In [15]:
np.linspace(0,100,3,retstep=True)

(array([  0.,  50., 100.]), 50.0)

####  distinguish between arange and linspace, arange require input step to generate, while linspace require num of element to be generated

####  create matrices identity

In [16]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

####  create random array (uniform distribution) 0-1

In [18]:
np.random.rand(5)

array([0.04049077, 0.82770519, 0.08707775, 0.73925199, 0.62711597])

In [19]:
np.random.rand(2,2)

array([[0.14613078, 0.07464227],
       [0.25141623, 0.45158626]])

#### create random array (normal distribution)

In [23]:
np.random.randn(2,5)

array([[ 0.09328117,  0.04497876, -0.04107264,  0.6623455 ,  0.02980966],
       [ 1.51578984, -0.10399812,  0.01565345, -0.01940201,  0.61052403]])

#### create random array of integer

In [37]:
j = 10
j = np.random.randint(1,100) #only return 1 intger
print("rand numb is {} as {}".format(j,type(j)))

rand numb is 6 as <class 'int'>


In [48]:
k = np.zeros((0,0))
k = np.random.randint(1,100,5)  #return random 5 number ranged 1-100
print("rand numb is {} as {}".format(k,type(k)))

rand numb is [86 87 72 79 80] as <class 'numpy.ndarray'>


#### reshaping array, input shape must be equal to output (remain unchanged)

In [51]:
randarr = np.arange(0,10)

In [52]:
randarr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [55]:
randarr = np.arange(0,25)

In [56]:
randarr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
randarr.reshape(4,6)

ValueError: cannot reshape array of size 25 into shape (4,6)

#### useful method to find max and min in array

In [58]:
randarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [59]:
randarr.max()

24

In [60]:
randarr.min()

0

In [61]:
randarr = np.random.randint(0,50,10)

In [62]:
randarr

array([29, 20, 16,  9, 16, 14,  3, 24, 45, 33])

In [63]:
randarr.max()

45

In [64]:
randarr.min()

3

#### get index of method (max/min)

In [65]:
randarr.argmax()

8

In [66]:
randarr.argmin()

6

#### shape and reshape of array

In [68]:
arr = np.random.randint(0,70,25)

In [70]:
arr

array([20, 37, 30,  7, 58, 34, 29,  3, 56, 39, 42, 14,  1,  7, 51, 63, 22,
       58,  1, 29, 50, 15, 57, 29, 17])

In [73]:
arr = arr.reshape(5,5)

In [74]:
arr

array([[20, 37, 30,  7, 58],
       [34, 29,  3, 56, 39],
       [42, 14,  1,  7, 51],
       [63, 22, 58,  1, 29],
       [50, 15, 57, 29, 17]])

In [75]:
arr.shape

(5, 5)

In [76]:
arr.dtype

dtype('int64')

#### slicing and indexing of array

In [78]:
arr = np.random.randint(0,100,11)

In [79]:
arr

array([80,  5, 29, 37,  3, 35, 46, 42,  3,  5, 19])

In [80]:
arr[5]

35

In [81]:
arr[0]

80

In [82]:
arr[1:3]

array([ 5, 29])

In [83]:
arr[0:5]

array([80,  5, 29, 37,  3])

In [84]:
arr[:7]

array([80,  5, 29, 37,  3, 35, 46])

In [85]:
arr[2:]

array([29, 37,  3, 35, 46, 42,  3,  5, 19])

#### broadcasting array value, broadcast replace the value of the array to desired input

In [86]:
sliceku = arr

In [87]:
sliceku

array([80,  5, 29, 37,  3, 35, 46, 42,  3,  5, 19])

In [88]:
sliceku[0:3]

array([80,  5, 29])

In [89]:
sliceku[0:3] = 69

In [90]:
sliceku

array([69, 69, 69, 37,  3, 35, 46, 42,  3,  5, 19])

In [91]:
arr

array([69, 69, 69, 37,  3, 35, 46, 42,  3,  5, 19])

#### basically any changes of array (sliceku) will be changed from its origin of the array (arr) aswell, numpy did this to avoid memory issue, but use copy instead to completely copy the whole array into new numpy variable.

In [92]:
arr

array([69, 69, 69, 37,  3, 35, 46, 42,  3,  5, 19])

In [93]:
arr_new = arr.copy()

In [94]:
arr_new[:] = 100

In [95]:
arr_new

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [96]:
arr

array([69, 69, 69, 37,  3, 35, 46, 42,  3,  5, 19])

#### grabbing array value from 2d matrices, could be using double bracket or commas notation

In [97]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]

In [98]:
my_arr = np.array(my_list)

In [99]:
my_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
my_arr[1][0]

4

In [101]:
my_arr[2][2]

9

In [102]:
my_arr[1,2]

6

In [103]:
my_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
my_arr[0:2] #from row 0 till row 2

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
my_arr[0:2,0:1] #grab from col 0 till 1

array([[1],
       [4]])

In [112]:
my_arr[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [116]:
my_arr[1:2]

array([[4, 5, 6]])

In [121]:
x = my_arr[1:2,1:2]

In [122]:
x

array([[5]])

In [123]:
my_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
my_arr = np.random.randint(0,20,10)

#### conditional array operation

In [126]:
my_arr

array([19, 14, 11, 17, 15, 19, 16,  3, 10,  1])

#### getting boolean statement of conditional in array

In [129]:
bool_arr = my_arr%2 == 0

In [130]:
bool_arr

array([False,  True, False, False, False, False,  True, False,  True,
       False])

#### grabbing array with true statement array from its origin array

In [142]:
new_arr = my_arr[bool_arr]

In [143]:
new_arr

array([14, 16, 10])

In [146]:
new_arr = my_arr[my_arr<10]

In [147]:
new_arr

array([3, 1])

#### create 2d array from random

In [149]:
rand_2d = np.random.randint(0,10,10)

In [150]:
rand_2d.reshape(2,5)

array([[1, 3, 0, 7, 2],
       [4, 5, 0, 7, 9]])

In [151]:
rand_2d = np.arange(0,50).reshape(5,10)

In [152]:
rand_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [153]:
rand_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [154]:
rand_2d[1:3,3:6]

array([[13, 14, 15],
       [23, 24, 25]])

#### array operation

In [155]:
new_arr = np.arange(0,10)

In [156]:
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
new_arr = new_arr+new_arr

In [158]:
new_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [159]:
new_arr + 100 #apply to whole elements of the array

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118])

In [161]:
0/new_arr #giving error but runtime still executing

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [163]:
np.sqrt(new_arr)    #SQUARE ROOT

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069])

In [164]:
np.max(new_arr)

18

In [165]:
np.exp(new_arr)

array([1.00000000e+00, 7.38905610e+00, 5.45981500e+01, 4.03428793e+02,
       2.98095799e+03, 2.20264658e+04, 1.62754791e+05, 1.20260428e+06,
       8.88611052e+06, 6.56599691e+07])

In [166]:
np.sin(new_arr) #sinus func

array([ 0.        ,  0.90929743, -0.7568025 , -0.2794155 ,  0.98935825,
       -0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725])

In [172]:
j= np.divide(new_arr,2)
j

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [168]:
new_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [173]:
type(j)

numpy.ndarray

In [175]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [195]:
mat = np.arange(1,26).reshape(5,5)

In [196]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [197]:
mat = mat[2:,1:]

In [198]:
mat

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])